# These parameters can be imported into other config files
# by enclosing the key with % (like %database_user%)
parameters:
    public_procedure_route: 'core_procedure_slug'
    procedure_creat_url: 'https://mein.berlin.de/api/organisations/<organisation-id>/bplan/'
    procedure_update_url: 'https://mein.berlin.de/api/organisations/<organisation-id>/bplan/<bplan-id>/'
    meinBerlinAuthorization: ''
